# NumPy

https://numpy.org/

In [1]:
# Importando o Numpy
import numpy as dsa

In [2]:
dsa.__version__

'1.21.5'

# Criando Arrays Numpy

In [3]:
# Array criado a partir de uma lista Python
arr1 = dsa.array([10, 21, 32, 43, 48, 15, 76, 57, 89])

In [4]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [5]:
# Um objeto do tipo ndarray é um recpiente multidimensional de itens do mesmo tipo e tamanho
type(arr1)

numpy.ndarray

In [6]:
# Verificando o formato do array
arr1.shape

(9,)

Um array NumPy é uma estrutura de dados multidimensionais usadas em computação cientifica e analise de dados. O NumPy fornece um objeto de matriz N-dimensional(ou ndarray), que e uma grade homogenea de elementos, geralmente numeros que podem ser indexados por um conjunto de inteiros.

# Indexação em Arrays NumPy

In [7]:
print(arr1)

[10 21 32 43 48 15 76 57 89]


In [8]:
# Imprimindo um elemento espcifico no array 
arr1[4]

48

In [9]:
# Indexação
arr1[1:4]

array([21, 32, 43])

In [10]:
# Indexação
arr1[1:4+1]

array([21, 32, 43, 48])

In [11]:
# Criando uma lista de de índices
indices = [1, 2, 5, 6]

In [12]:
# Imprimindo os elementos dos indices
arr1[indices]

array([21, 32, 15, 76])

In [13]:
# Cria uma mascara booleana para os elementos pares 
mask = (arr1 % 2 == 0)

In [14]:
arr1[mask]

array([10, 32, 48, 76])

In [15]:
# Alterando um elemento do array 
arr1[0] = 100

In [16]:
print(arr1)

[100  21  32  43  48  15  76  57  89]


# Fim